In [48]:
import pandas as pd
import numpy as np

In [49]:
df=pd.read_csv('Advertising.csv')

In [50]:
df.head()

   ID     TV  Radio  Newspaper  Sales
0   1  230.1   37.8       69.2   22.1
1   2   44.5   39.3       45.1   10.4
2   3   17.2   45.9       69.3    9.3
3   4  151.5   41.3       58.5   18.5
4   5  180.8   10.8       58.4   12.9

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         200 non-null    int64
 1   TV         200 non-null    float64
 2   Radio      200 non-null    float64
 3   Newspaper  200 non-null    float64
 4   Sales      200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.describe()

               ID          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [54]:
df=df.drop('ID',axis=1)

In [55]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [56]:
X=df.drop('Sales',axis=1)
y=df["Sales"]

In [57]:
y.shape

(200,)

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [59]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [60]:
model.fit(X_train,y_train)

LinearRegression()

In [61]:
y_predtest=model.predict(X_test)

In [62]:
from sklearn.metrics import mean_squared_error,r2_score

In [63]:
mean_squared_error(y_predtest,y_test)

3.174097353976104

In [64]:
r2_score(y_predtest,y_test)

0.8791069137120033

In [65]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [66]:
def sales(TV, Radio, Newspaper):
    return model.predict([[TV, Radio, Newspaper]])

In [72]:
tv=float(input('enter the price of tv'))
radion=float(input('enter the redion price'))
newspaper=float(input('enter the newspaper price'))
print(f'''the sales prices is \n {sales(tv, radion, newspaper)}''')

enter the price of tv 222
enter the redion price 212
enter the newspaper price 432

the sales prices is
 [54.21117311]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(